name: CI Pipeline

on:
  push:
    branches:
      - main   # Triggers the pipeline on every push to 'main' branch
  pull_request:
    branches:
      - main   # Triggers the pipeline on pull requests targeting 'main'

jobs:
  build:
    runs-on: windows-latest  # Use the latest Windows runner
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Fetches the code from GitHub repository

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'  # Specify the version of .NET you are using
    
    - name: Install dependencies
      run: |
        dotnet restore  # Installs the NuGet dependencies
    
    - name: Run unit tests
      run: |
        dotnet test --filter "FullyQualifiedName~UnitTests"

    - name: Run API tests
      run: |
        dotnet test --filter "FullyQualifiedName~ApiTests"

    - name: Install Playwright Browsers
      run: pwsh ./bin/Debug/net8.0/playwright.ps1 install

    - name: Run UI tests
      run: |
        dotnet test --filter "FullyQualifiedName~UITests"
